version: '3.8'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: office_desk_db
    user: root
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=SuperSecret_Password_123!
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: office_desk_api
    depends_on:
      - db
    ports:
      - "5000:8080" 
    environment:
      - ConnectionStrings__DefaultConnection=Server=db;Database=OfficeDeskReservationDb;User Id=sa;Password=SuperSecret_Password_123!;TrustServerCertificate=True;
      - ASPNETCORE_ENVIRONMENT=Production 

  ui:
    build:
      context: .
      dockerfile: Dockerfile.ui
    container_name: office_desk_ui
    depends_on:
      - api
    ports:
      - "8080:80" 
    restart: always

volumes:
  sql_data: