FROM node:20 AS build
WORKDIR /app

COPY OfficeDeskReservation.UI/package*.json ./
RUN npm install

COPY OfficeDeskReservation.UI/ ./
RUN npm run build -- --configuration production

FROM nginx:alpine
COPY --from=build /app/dist/OfficeDeskReservation.UI/browser /usr/share/nginx/html

COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]